language: node_js
node_js:
  - 6
env:
  - CXX=g++-4.8
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
    - master
before_install:
  - export TZ=America/Denver
  - date
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
sudo: false
notifications:
  slack:
    secure: NYuPalo0BOFnYF5jnLz1Y5uHrusbqQGKl/DlQ/SGXXsJycclBex0tvHT4DmXE5tpxIixGOi9IilrXNkfU47rV0pZ4aKxWivdbtGeNwn51lTUQyOr5NWKQ/ajTT2Yxpmi6aAsZHVU9mvLJwfq0L689uzRI0PmPq//Ollo4QFTduY=
after_success:
  - codeclimate-test-reporter < reports/coverage/lcov.info